@startuml

    !includesub ../../CERIF-Core/diagrams/core.puml!common
    !includesub ../../CERIF-Core/diagrams/core.puml!Resource
    !includesub ../../CERIF-Core/diagrams/core.puml!Infrastructure
    !includesub ../../CERIF-Core/diagrams/core.puml!Contribution_to_Infrastructure
    !includesub ../../CERIF-Core/diagrams/core.puml!Contribution
    !includesub ../../CERIF-Core/diagrams/core.puml!Activity
    !includesub ../../CERIF-Core/diagrams/core.puml!Agent
    !includesub ../../CERIF-Core/diagrams/core.puml!Date_Range
    !includesub ../../CERIF-Core/diagrams/core.puml!Contribution_Statement
    !includesub ../../CERIF-Core/diagrams/core.puml!Resource_Usage_Statement
    !includesub ../../CERIF-Core/diagrams/core.puml!Resource_Identifier

    !startsub Instrument_Instance
        class "Instrument_Instance" #d8f0d8 {
        }

        "Infrastructure" <|-- "Instrument_Instance"
    !endsub

    !startsub Instrument_Model
        class "Instrument_Model" #d8f0d8 {
        }

        "Infrastructure" <|-- "Instrument_Model"
    !endsub

    !startsub Instrument_Instance
        "Instrument_Instance" "0..*" -- "0..1" "Instrument_Model" : is instance of >
    !endsub

    !startsub Infrastructure_Ownership
        class "Infrastructure_Ownership" #d8f0d8 {
        }

        "Contribution_to_Infrastructure" <|-- "Infrastructure_Ownership"
    !endsub

    !startsub Infrastructure_Operation
        class "Infrastructure_Operation" #d8f0d8 {
        }

        "Contribution_to_Infrastructure" <|-- "Infrastructure_Operation"
    !endsub

    !startsub Manufacturing
        class "Manufacturing" #d8f0d8 {
        }

        "Contribution_to_Infrastructure" <|-- "Manufacturing"
    !endsub

    !startsub Instrument_Instance_Identifier
        class "Instrument_Instance_Identifier" #d8f0d8 {
        }

        "Resource_Identifier" <|-- "Instrument_Instance_Identifier"
    !endsub

    !startsub Serial_Number
        class "Serial_Number" #d8f0d8 {
            serialNumber : String
        }

        "Instrument_Instance_Identifier" <|-- "Serial_Number"
    !endsub

    !startsub Inventory_Number
        class "Inventory_Number" #d8f0d8 {
            inventoryNumber : String
        }

        "Instrument_Instance_Identifier" <|-- "Inventory_Number"
    !endsub

    !startsub Other_Instrument_Instance_Identifier
        class "Other_Instrument_Instance_Identifier" #d8f0d8 {
        }

        "Instrument_Instance_Identifier" <|-- "Other_Instrument_Instance_Identifier"
    !endsub

    !startsub Instrument_Model_Identifier
        class "Instrument_Model_Identifier" #d8f0d8 {
            modelDesignation : String
        }

        "Resource_Identifier" <|-- "Instrument_Model_Identifier"
    !endsub

@enduml
