@startuml

    !includesub ../../CERIF-Core/diagrams/core.puml!common
    !includesub ../../CERIF-Core/diagrams/core.puml!Resource
    !includesub ../../CERIF-Core/diagrams/core.puml!Infrastructure

    !startsub Instrument_Instance
        class "Instrument_Instance" #d8f0d8 {
        }

        "Infrastructure" <|-- "Instrument_Instance"
    !endsub

    !startsub Instrument_Model
        class "Instrument_Model" #d8f0d8 {
        }

        "Infrastructure" <|-- "Instrument_Model"
    !endsub

    !startsub Instrument_Instance
        "Instrument_Instance" "0..*" -- "0..1" "Instrument_Model" : is instance of >
    !endsub

@enduml
